/*
 * This source file was generated by the Gradle 'init' task
 */
package org.scraper

import org.openqa.selenium._;
import org.openqa.selenium.chrome.ChromeDriver;

import scala.jdk.CollectionConverters._;

object App {
  def main(args: Array[String]): Unit = {

    //System.setProperty("webdriver.chrome.driver", "../chromedriver_mac64/chromedriver");

    println(System.getProperty("user.dir"))

    val driver: WebDriver = new ChromeDriver();

    driver.get("https://jobs.apple.com/en-gb/search?location=united-kingdom-GBR");

    val textBox = driver.findElements(By.className("table-col-1")).asScala;

    for (job <- textBox){
      println(job.getText());
    }

  }

  def greeting(): String = "Hello, world!"
}
