/*
 * This source file was generated by the Gradle 'init' task
 */
package org.scraper

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.safari.SafariDriver;

object App {
  def main(args: Array[String]): Unit = {

    val driver: WebDriver = new SafariDriver();

    // driver.get("https://jobs.apple.com/en-gb/search?location=united-kingdom-GBR")

    // WebElement textBox = driver.findElement(By.name("table-col-1"));

    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
